language: python

cache:
    apt
    pip
python:
  - 2.7
  - 3.5
  - pypy
env:
    - ZMQ=
    - ZMQ=bundled
before_install:
  - sudo add-apt-repository -y ppa:anton+/dnscrypt
  - sudo apt-get update
  - |
    if [[ $ZMQ != bundled ]]; then
      sudo apt-get install -y -qq libzmq3-dev libsodium-dev
    fi
  - |
    if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then
      pip install -q cython --install-option="--no-cython-compile"
    fi
  - |
    if [[ ! -z "$ZMQ" && $ZMQ != bundled ]]; then
      wget https://github.com/zeromq/$ZMQ/archive/master.zip -O libzmq.zip
      unzip libzmq.zip
      pushd "$ZMQ-master"
      ./autogen.sh
      ./configure
      make -j
      sudo make install
      sudo ldconfig
      popd
      export ZMQ=/usr/local
    fi
  - pip install -r test-requirements.txt

install:
  - python setup.py build_ext --inplace --zmq=$ZMQ

matrix:
  include:
    - python: 3.6-dev
      env: ZMQ=bundled
    - python: 3.5
      env: ZMQ=libzmq
    - python: 3.4
      env: ZMQ=zeromq4-x
    - python: 3.4
      env: ZMQ=zeromq4-1
    - python: 3.4
      env: ZMQ=zeromq3-x
    - python: 3.3
      env: ZMQ=
    # FIXME: pypy3 is still on unsupported Python 3.2
    # - python: pypy3
    #   env: ZMQ=
    - python: nightly
      env: ZMQ=
    - python: nightly
      env: ZMQ=bundled
  allow_failures:
    - env: ZMQ=libzmq
    - python: nightly

script: travis_retry python setup.py test
